version: 2.1

parameters:
  trigger:
    type: boolean
    default: false

jobs:
  trigger-workflows:
    executor: python
    steps:
      - run: echo "$(pwd) , << pipeline.parameters.trigger >>"

workflows:
  version: 2
  dev:
    jobs:
      - trigger-workflows