version: 2.1

parameters:
  trigger:
    type: boolean
    default: false

executors:
  nodejs:
    docker:
      - image: circleci/node:14

jobs:
  trigger-workflows:
    executor: nodejs
    steps:
      - run: echo "This is production deploy"

workflows:
  version: 2
  production-deploy:
    jobs:
      - trigger-workflows