# version of CircleCI
version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.2.0

# our defined parameters.
parameters:
  deploy:
    default: "staging"
    type: string

commands:
  check-deploy:
    steps:
      - run:
          name: Check deploy structure.
          command: |
            [ "$(ls -A .circleci/deploy/<< pipeline.parameters.deploy >>)" ] && 
            echo "OK" ||
            circleci step halt

# our defined job, and its steps.
jobs:
  deploy:
    executor: continuation/default
    steps:
      - checkout
      - check-deploy
      - continuation/continue:
          configuration_path: .circleci/deploy/<< pipeline.parameters.deploy >>/config.yml
          parameters: .circleci/deploy/<< pipeline.parameters.deploy >>/param.json

# our workflows.
workflows:
  version: 2
  setup:
    jobs:
      - deploy
