version: 2.1

parameters:
  deploy:
  test:

executors:
  nodejs:
    docker:
      - image: circleci/node:14

jobs:
  trigger-jobs:
    executor: nodejs
    steps:
      - run:
          name: "This is STAGING deploy"
          command: |
            echo "This is first command"
      - run:
          name: "Display parameters"
          command: |
            echo "This is deploy value << pipeline.parameters.deploy >>"
            echo "This is test value << pipeline.parameters.test >>"
      - run:
          name: "Display context"
          command: |
            echo $DOMAIN

workflows:
  version: 2
  staging-deploy:
    jobs:
      - trigger-jobs:
          context:
            - STAGING