version: 2.1

parameters:
  deploy:
    type: string
    default: "staging"
  node-version:
    type: string
    default: "14"

executors:
  node-js:
    docker:
      - image: circleci/node:<< pipeline.parameters.node-version >>

jobs:
  trigger-jobs:
    executor: node-js
    steps:
      - run:
          name: "This is PRODUCTION deploy"
          command: |
            echo "This is first command"
      - run:
          name: "Display parameters"
          command: |
            echo "This is deploy value << pipeline.parameters.deploy >>"
            echo "This is test value << pipeline.parameters.test >>"
      - run:
          name: "Display context"
          command: |
            echo $DOMAIN

workflows:
  version: 2
  production-deploy:
    jobs:
      - trigger-jobs:
          context:
            - PRODUCTION