version: 2.1

parameters:
  setup_dev:
    type: boolean
    default: false
  setup_staging:
    type: boolean
    default: false
  setup_production:
    type: boolean
    default: false

executors:
  nodejs:
    docker:
      - image: circleci/node:14

jobs:
  trigger-workflows:
    executor: nodejs
    steps:
      - run: echo "This is staging deploy"

workflows:
  version: 2
  dev-deploy:
    jobs:
      - trigger-workflows