version: 2.1

parameters:
  env:
    default: "dev"
    type: enum
    enum: ["dev", "staging", "production"]

executors:
  nodejs:
    docker:
      - image: circleci/node:14

jobs:
  trigger-workflow:
    executor: nodejs
    steps:
      - run:
          name: "This is DEV deploy"
          command: |
            echo "This is first command"
      - run:
          name: "Display parameters"
          command: |
            echo "This is env value << pipeline.parameters.env >>"
      - run:
          name: "Display context"
          command: |
            echo "$DOMAIN"

workflows:
  version: 2
  dev-deploy:
    jobs:
      - trigger-workflow:
          context:
            - DEV