version: 2.1

parameters:
  env:
    default: "dev"
    type: enum
    enum: ["dev", "staging", "production"]

executors:
  nodejs:
    docker:
      - image: circleci/node:14

jobs:
  trigger-workflows:
    executor: nodejs
    steps:
      - run: echo "This is staging deploy"

workflows:
  version: 2
  dev-deploy:
    jobs:
      - trigger-workflows